#!/bin/bash

################################################################################
# Shopify Analytics Tables Setup Script
# 
# This script creates dimension tables, fact tables, and aggregate rollup 
# tables for Shopify analytics on macOS.
#
# Features:
# - Creates dimension tables (customers, channels)
# - Creates fact tables (orders, channel performance)
# - Creates aggregate rollup tables (daily, customer LTV, cohorts)
# - Supports both H2 (development) and PostgreSQL (production)
# - Includes sample rollup queries
#
# Usage:
#   ./setup_shopify_analytics.sh [h2|postgres] [db_url] [db_user] [db_password]
#
# Examples:
#   # For H2 (in-memory):
#   ./setup_shopify_analytics.sh h2
#
#   # For PostgreSQL:
#   ./setup_shopify_analytics.sh postgres "jdbc:postgresql://localhost:5432/analytics" "postgres" "password"
#
################################################################################

set -e  # Exit on any error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to display usage
usage() {
    cat << EOF
Usage: $0 [h2|postgres] [db_url] [db_user] [db_password]

Arguments:
  db_type     Database type: h2 or postgres (default: h2)
  db_url      Database connection URL (required for postgres)
  db_user     Database username (required for postgres)
  db_password Database password (required for postgres)

Examples:
  # For H2 (in-memory):
  $0 h2

  # For PostgreSQL:
  $0 postgres "jdbc:postgresql://localhost:5432/analytics" "postgres" "password"

EOF
    exit 1
}

# Parse arguments
DB_TYPE=${1:-h2}
DB_URL=$2
DB_USER=$3
DB_PASSWORD=$4

# Validate arguments
if [[ "$DB_TYPE" != "h2" && "$DB_TYPE" != "postgres" ]]; then
    print_error "Invalid database type: $DB_TYPE"
    usage
fi

if [[ "$DB_TYPE" == "postgres" ]]; then
    if [[ -z "$DB_URL" || -z "$DB_USER" || -z "$DB_PASSWORD" ]]; then
        print_error "PostgreSQL requires db_url, db_user, and db_password"
        usage
    fi
fi

print_info "Starting Shopify Analytics Tables Setup"
print_info "Database Type: $DB_TYPE"

################################################################################
# SQL Scripts
################################################################################

# Create temporary SQL file
TMP_SQL_FILE="/tmp/shopify_analytics_$(date +%s).sql"

if [[ "$DB_TYPE" == "h2" ]]; then
    cat > "$TMP_SQL_FILE" << 'EOF'
-- ============================================================================
-- SHOPIFY ANALYTICS SCHEMA - H2 VERSION
-- ============================================================================

-- ============================================================================
-- SHOPS TABLE (Base dimension)
-- ============================================================================
CREATE TABLE IF NOT EXISTS shops (
  shop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_domain VARCHAR(255) NOT NULL UNIQUE,
  currency VARCHAR(3) NOT NULL,
  timezone VARCHAR(64) NOT NULL,
  last_backfill_through TIMESTAMP,
  last_incremental_sync_at TIMESTAMP,
  shopify_access_token_encrypted VARCHAR(512),
  shopify_access_token_iv VARCHAR(64),
  shopify_scopes VARCHAR(512),
  shopify_installed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP,
  deleted_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_shops_domain ON shops (shop_domain);

-- ============================================================================
-- DIMENSION TABLE: dim_customers
-- Stores customer information for analytics
-- ============================================================================
CREATE TABLE IF NOT EXISTS dim_customers (
  shop_id BIGINT NOT NULL,
  customer_gid VARCHAR(128) NOT NULL,
  email VARCHAR(320),
  email_hash VARCHAR(128),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  first_order_processed_at TIMESTAMP,
  last_order_processed_at TIMESTAMP,
  PRIMARY KEY (shop_id, customer_gid),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dim_customers_shop_email ON dim_customers (shop_id, email);
CREATE INDEX IF NOT EXISTS idx_dim_customers_shop_first_order ON dim_customers (shop_id, first_order_processed_at);

-- ============================================================================
-- DIMENSION TABLE: dim_channel
-- Stores marketing channel information
-- ============================================================================
CREATE TABLE IF NOT EXISTS dim_channel (
  channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_key VARCHAR(64) NOT NULL UNIQUE,
  channel_name VARCHAR(128) NOT NULL,
  channel_type VARCHAR(32) NOT NULL CHECK (channel_type IN ('paid', 'organic', 'marketplace')),
  status VARCHAR(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled'))
);

-- ============================================================================
-- FACT TABLE: fact_orders
-- Stores individual order transactions
-- ============================================================================
CREATE TABLE IF NOT EXISTS fact_orders (
  shop_id BIGINT NOT NULL,
  order_gid VARCHAR(128) NOT NULL,
  order_name VARCHAR(128),
  created_at TIMESTAMP,
  processed_at TIMESTAMP,
  updated_at TIMESTAMP,
  cancelled_at TIMESTAMP,
  financial_status VARCHAR(32),
  customer_gid VARCHAR(128),
  gross_total DECIMAL(14,2),
  gross_tax DECIMAL(14,2),
  gross_shipping DECIMAL(14,2),
  net_sales DECIMAL(14,2),
  is_new_customer BOOLEAN,
  PRIMARY KEY (shop_id, order_gid),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fact_orders_shop_processed ON fact_orders (shop_id, processed_at);
CREATE INDEX IF NOT EXISTS idx_fact_orders_shop_updated ON fact_orders (shop_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_fact_orders_shop_customer ON fact_orders (shop_id, customer_gid);

-- ============================================================================
-- FACT TABLE: fact_channel_day
-- Stores daily marketing channel performance metrics
-- ============================================================================
CREATE TABLE IF NOT EXISTS fact_channel_day (
  shop_id BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  date DATE NOT NULL,
  spend DECIMAL(14,2) DEFAULT 0 NOT NULL,
  impressions BIGINT DEFAULT 0 NOT NULL,
  clicks BIGINT DEFAULT 0 NOT NULL,
  attributed_revenue DECIMAL(14,2) DEFAULT 0 NOT NULL,
  attributed_orders INT DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, channel_id, date),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE,
  FOREIGN KEY (channel_id) REFERENCES dim_channel(channel_id)
);

CREATE INDEX IF NOT EXISTS idx_fact_channel_day_shop_date ON fact_channel_day (shop_id, date);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_shop_day
-- Daily rollup of shop-level metrics
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_shop_day (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  orders_count INT DEFAULT 0 NOT NULL,
  revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  tax_total DECIMAL(14,2) DEFAULT 0 NOT NULL,
  shipping_total DECIMAL(14,2) DEFAULT 0 NOT NULL,
  new_orders_count INT DEFAULT 0 NOT NULL,
  returning_orders_count INT DEFAULT 0 NOT NULL,
  new_revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  returning_revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, date),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agg_shop_day_date ON agg_shop_day (date);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_customer_ltv
-- Customer lifetime value metrics
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_customer_ltv (
  shop_id BIGINT NOT NULL,
  customer_gid VARCHAR(128) NOT NULL,
  first_order_processed_at TIMESTAMP,
  last_order_processed_at TIMESTAMP,
  lifetime_orders_count INT DEFAULT 0 NOT NULL,
  lifetime_revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  lifetime_net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, customer_gid),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agg_customer_ltv_shop_first ON agg_customer_ltv (shop_id, first_order_processed_at);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_ltv_cohort_month
-- Monthly cohort analysis for customer lifetime value
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_ltv_cohort_month (
  shop_id BIGINT NOT NULL,
  cohort_month DATE NOT NULL,
  months_since_first_order INT NOT NULL,
  customers_in_cohort INT DEFAULT 0 NOT NULL,
  net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  cumulative_net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, cohort_month, months_since_first_order),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agg_ltv_cohort_month_shop ON agg_ltv_cohort_month (shop_id, cohort_month);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_shop_day_with_spend
-- Daily shop metrics combined with ad spend
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_shop_day_with_spend (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  orders_count INT DEFAULT 0 NOT NULL,
  ad_spend_total DECIMAL(14,2) DEFAULT 0 NOT NULL,
  mer DECIMAL(14,6) DEFAULT 0 NOT NULL,  -- Marketing Efficiency Ratio
  PRIMARY KEY (shop_id, date),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agg_shop_day_with_spend_date ON agg_shop_day_with_spend (date);

-- ============================================================================
-- RAW PAYLOAD TABLES (for integration data storage)
-- ============================================================================
CREATE TABLE IF NOT EXISTS raw_meta_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_raw_meta_ads_shop_date ON raw_meta_ads (shop_id, date);

CREATE TABLE IF NOT EXISTS raw_google_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_raw_google_ads_shop_date ON raw_google_ads (shop_id, date);

EOF

elif [[ "$DB_TYPE" == "postgres" ]]; then
    cat > "$TMP_SQL_FILE" << 'EOF'
-- ============================================================================
-- SHOPIFY ANALYTICS SCHEMA - PostgreSQL VERSION
-- ============================================================================

-- ============================================================================
-- SHOPS TABLE (Base dimension)
-- ============================================================================
CREATE TABLE IF NOT EXISTS shops (
  shop_id BIGSERIAL PRIMARY KEY,
  shop_domain TEXT NOT NULL UNIQUE,
  currency VARCHAR(3) NOT NULL,
  timezone TEXT NOT NULL,
  last_backfill_through TIMESTAMP,
  last_incremental_sync_at TIMESTAMP,
  shopify_access_token_encrypted TEXT,
  shopify_access_token_iv TEXT,
  shopify_scopes TEXT,
  shopify_installed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP,
  deleted_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_shops_domain ON shops (shop_domain);

-- ============================================================================
-- DIMENSION TABLE: dim_customers
-- Stores customer information for analytics
-- ============================================================================
CREATE TABLE IF NOT EXISTS dim_customers (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  customer_gid TEXT NOT NULL,
  email TEXT,
  email_hash TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  first_order_processed_at TIMESTAMP,
  last_order_processed_at TIMESTAMP,
  PRIMARY KEY (shop_id, customer_gid)
);

CREATE INDEX IF NOT EXISTS idx_dim_customers_shop_email ON dim_customers (shop_id, email);
CREATE INDEX IF NOT EXISTS idx_dim_customers_shop_first_order ON dim_customers (shop_id, first_order_processed_at);

-- ============================================================================
-- DIMENSION TABLE: dim_channel
-- Stores marketing channel information
-- ============================================================================
CREATE TABLE IF NOT EXISTS dim_channel (
  channel_id BIGSERIAL PRIMARY KEY,
  channel_key TEXT NOT NULL UNIQUE,
  channel_name TEXT NOT NULL,
  channel_type TEXT NOT NULL CHECK (channel_type IN ('paid', 'organic', 'marketplace')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled'))
);

-- ============================================================================
-- FACT TABLE: fact_orders
-- Stores individual order transactions
-- ============================================================================
CREATE TABLE IF NOT EXISTS fact_orders (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  order_gid TEXT NOT NULL,
  order_name TEXT,
  created_at TIMESTAMP,
  processed_at TIMESTAMP,
  updated_at TIMESTAMP,
  cancelled_at TIMESTAMP,
  financial_status TEXT,
  customer_gid TEXT,
  gross_total NUMERIC(14,2),
  gross_tax NUMERIC(14,2),
  gross_shipping NUMERIC(14,2),
  net_sales NUMERIC(14,2),
  is_new_customer BOOLEAN,
  PRIMARY KEY (shop_id, order_gid)
);

CREATE INDEX IF NOT EXISTS idx_fact_orders_shop_processed ON fact_orders (shop_id, processed_at);
CREATE INDEX IF NOT EXISTS idx_fact_orders_shop_updated ON fact_orders (shop_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_fact_orders_shop_customer ON fact_orders (shop_id, customer_gid);

-- ============================================================================
-- FACT TABLE: fact_channel_day
-- Stores daily marketing channel performance metrics
-- ============================================================================
CREATE TABLE IF NOT EXISTS fact_channel_day (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  channel_id BIGINT NOT NULL REFERENCES dim_channel(channel_id),
  date DATE NOT NULL,
  spend NUMERIC(14,2) DEFAULT 0 NOT NULL,
  impressions BIGINT DEFAULT 0 NOT NULL,
  clicks BIGINT DEFAULT 0 NOT NULL,
  attributed_revenue NUMERIC(14,2) DEFAULT 0 NOT NULL,
  attributed_orders INT DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, channel_id, date)
);

CREATE INDEX IF NOT EXISTS idx_fact_channel_day_shop_date ON fact_channel_day (shop_id, date);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_shop_day
-- Daily rollup of shop-level metrics
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_shop_day (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  date DATE NOT NULL,
  orders_count INT DEFAULT 0 NOT NULL,
  revenue_gross NUMERIC(14,2) DEFAULT 0 NOT NULL,
  net_sales NUMERIC(14,2) DEFAULT 0 NOT NULL,
  tax_total NUMERIC(14,2) DEFAULT 0 NOT NULL,
  shipping_total NUMERIC(14,2) DEFAULT 0 NOT NULL,
  new_orders_count INT DEFAULT 0 NOT NULL,
  returning_orders_count INT DEFAULT 0 NOT NULL,
  new_revenue_gross NUMERIC(14,2) DEFAULT 0 NOT NULL,
  returning_revenue_gross NUMERIC(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, date)
);

CREATE INDEX IF NOT EXISTS idx_agg_shop_day_date ON agg_shop_day (date);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_customer_ltv
-- Customer lifetime value metrics
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_customer_ltv (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  customer_gid TEXT NOT NULL,
  first_order_processed_at TIMESTAMP,
  last_order_processed_at TIMESTAMP,
  lifetime_orders_count INT DEFAULT 0 NOT NULL,
  lifetime_revenue_gross NUMERIC(14,2) DEFAULT 0 NOT NULL,
  lifetime_net_sales NUMERIC(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, customer_gid)
);

CREATE INDEX IF NOT EXISTS idx_agg_customer_ltv_shop_first ON agg_customer_ltv (shop_id, first_order_processed_at);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_ltv_cohort_month
-- Monthly cohort analysis for customer lifetime value
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_ltv_cohort_month (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  cohort_month DATE NOT NULL,
  months_since_first_order INT NOT NULL,
  customers_in_cohort INT DEFAULT 0 NOT NULL,
  net_sales NUMERIC(14,2) DEFAULT 0 NOT NULL,
  cumulative_net_sales NUMERIC(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, cohort_month, months_since_first_order)
);

CREATE INDEX IF NOT EXISTS idx_agg_ltv_cohort_month_shop ON agg_ltv_cohort_month (shop_id, cohort_month);

-- ============================================================================
-- AGGREGATE/ROLLUP TABLE: agg_shop_day_with_spend
-- Daily shop metrics combined with ad spend
-- ============================================================================
CREATE TABLE IF NOT EXISTS agg_shop_day_with_spend (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  date DATE NOT NULL,
  revenue_gross NUMERIC(14,2) DEFAULT 0 NOT NULL,
  net_sales NUMERIC(14,2) DEFAULT 0 NOT NULL,
  orders_count INT DEFAULT 0 NOT NULL,
  ad_spend_total NUMERIC(14,2) DEFAULT 0 NOT NULL,
  mer NUMERIC(14,6) DEFAULT 0 NOT NULL,  -- Marketing Efficiency Ratio
  PRIMARY KEY (shop_id, date)
);

CREATE INDEX IF NOT EXISTS idx_agg_shop_day_with_spend_date ON agg_shop_day_with_spend (date);

-- ============================================================================
-- RAW PAYLOAD TABLES (for integration data storage using JSONB)
-- ============================================================================
CREATE TABLE IF NOT EXISTS raw_meta_ads (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  date DATE NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (shop_id, date, created_at)
);

CREATE INDEX IF NOT EXISTS idx_raw_meta_ads_shop_date ON raw_meta_ads (shop_id, date);

CREATE TABLE IF NOT EXISTS raw_google_ads (
  shop_id BIGINT NOT NULL REFERENCES shops(shop_id) ON DELETE CASCADE,
  date DATE NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (shop_id, date, created_at)
);

CREATE INDEX IF NOT EXISTS idx_raw_google_ads_shop_date ON raw_google_ads (shop_id, date);

EOF
fi

print_success "SQL script generated: $TMP_SQL_FILE"

################################################################################
# Execute SQL
################################################################################

print_info "Executing SQL script..."

if [[ "$DB_TYPE" == "h2" ]]; then
    print_warning "H2 in-memory database is typically managed by the Spring Boot application"
    print_info "The schema will be automatically created when the application starts"
    print_info "You can also manually execute the SQL through H2 Console at: http://localhost:8080/h2"
    print_info "  - JDBC URL: jdbc:h2:mem:analytics"
    print_info "  - Username: sa"
    print_info "  - Password: (leave empty)"
    
    print_success "Schema definition ready at: $TMP_SQL_FILE"
    
elif [[ "$DB_TYPE" == "postgres" ]]; then
    # Check if psql is installed
    if ! command -v psql &> /dev/null; then
        print_error "psql command not found. Please install PostgreSQL client tools."
        print_info "You can install it using: brew install postgresql"
        exit 1
    fi
    
    # Extract database details from JDBC URL
    # Example: jdbc:postgresql://localhost:5432/analytics
    DB_HOST=$(echo "$DB_URL" | sed -n 's/.*:\/\/\([^:]*\):.*/\1/p')
    DB_PORT=$(echo "$DB_URL" | sed -n 's/.*:\([0-9]*\)\/.*/\1/p')
    DB_NAME=$(echo "$DB_URL" | sed -n 's/.*\/\([^?]*\).*/\1/p')
    
    print_info "Connecting to PostgreSQL..."
    print_info "  Host: $DB_HOST"
    print_info "  Port: $DB_PORT"
    print_info "  Database: $DB_NAME"
    print_info "  User: $DB_USER"
    
    # Execute SQL using psql
    PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -f "$TMP_SQL_FILE"
    
    if [[ $? -eq 0 ]]; then
        print_success "Tables created successfully in PostgreSQL"
    else
        print_error "Failed to execute SQL script"
        exit 1
    fi
fi

################################################################################
# Generate Rollup Query Examples
################################################################################

print_info "Generating rollup query examples..."

ROLLUP_QUERIES_FILE="/tmp/shopify_analytics_rollup_queries.sql"

cat > "$ROLLUP_QUERIES_FILE" << 'EOF'
-- ============================================================================
-- SHOPIFY ANALYTICS - ROLLUP QUERY EXAMPLES
-- ============================================================================
-- 
-- NOTE: These queries use PostgreSQL syntax (DATE_TRUNC, AGE, INTERVAL, etc.)
-- For H2, you would need to adapt these queries to H2-compatible syntax.
-- The aggregate tables are created by both H2 and PostgreSQL versions,
-- but these specific rollup queries are optimized for PostgreSQL.
--
-- For H2 users: The Spring Boot application handles aggregations in Java code.
-- ============================================================================

-- ============================================================================
-- ROLLUP 1: Populate Daily Shop Aggregates from Fact Orders
-- This query rolls up individual orders into daily summaries
-- ============================================================================
INSERT INTO agg_shop_day (
    shop_id,
    date,
    orders_count,
    revenue_gross,
    net_sales,
    tax_total,
    shipping_total,
    new_orders_count,
    returning_orders_count,
    new_revenue_gross,
    returning_revenue_gross
)
SELECT 
    shop_id,
    CAST(processed_at AS DATE) as date,
    COUNT(*) as orders_count,
    SUM(gross_total) as revenue_gross,
    SUM(net_sales) as net_sales,
    SUM(gross_tax) as tax_total,
    SUM(gross_shipping) as shipping_total,
    SUM(CASE WHEN is_new_customer = TRUE THEN 1 ELSE 0 END) as new_orders_count,
    SUM(CASE WHEN is_new_customer = FALSE THEN 1 ELSE 0 END) as returning_orders_count,
    SUM(CASE WHEN is_new_customer = TRUE THEN gross_total ELSE 0 END) as new_revenue_gross,
    SUM(CASE WHEN is_new_customer = FALSE THEN gross_total ELSE 0 END) as returning_revenue_gross
FROM fact_orders
WHERE cancelled_at IS NULL
  AND processed_at IS NOT NULL
GROUP BY shop_id, CAST(processed_at AS DATE)
ON CONFLICT (shop_id, date) DO UPDATE SET
    orders_count = EXCLUDED.orders_count,
    revenue_gross = EXCLUDED.revenue_gross,
    net_sales = EXCLUDED.net_sales,
    tax_total = EXCLUDED.tax_total,
    shipping_total = EXCLUDED.shipping_total,
    new_orders_count = EXCLUDED.new_orders_count,
    returning_orders_count = EXCLUDED.returning_orders_count,
    new_revenue_gross = EXCLUDED.new_revenue_gross,
    returning_revenue_gross = EXCLUDED.returning_revenue_gross;

-- ============================================================================
-- ROLLUP 2: Calculate Customer Lifetime Value (LTV)
-- This query aggregates all orders per customer to calculate LTV metrics
-- ============================================================================
INSERT INTO agg_customer_ltv (
    shop_id,
    customer_gid,
    first_order_processed_at,
    last_order_processed_at,
    lifetime_orders_count,
    lifetime_revenue_gross,
    lifetime_net_sales
)
SELECT 
    shop_id,
    customer_gid,
    MIN(processed_at) as first_order_processed_at,
    MAX(processed_at) as last_order_processed_at,
    COUNT(*) as lifetime_orders_count,
    SUM(gross_total) as lifetime_revenue_gross,
    SUM(net_sales) as lifetime_net_sales
FROM fact_orders
WHERE cancelled_at IS NULL
  AND processed_at IS NOT NULL
  AND customer_gid IS NOT NULL
GROUP BY shop_id, customer_gid
ON CONFLICT (shop_id, customer_gid) DO UPDATE SET
    first_order_processed_at = EXCLUDED.first_order_processed_at,
    last_order_processed_at = EXCLUDED.last_order_processed_at,
    lifetime_orders_count = EXCLUDED.lifetime_orders_count,
    lifetime_revenue_gross = EXCLUDED.lifetime_revenue_gross,
    lifetime_net_sales = EXCLUDED.lifetime_net_sales;

-- ============================================================================
-- ROLLUP 3: Calculate Cohort Analysis by Month
-- Groups customers by their first order month and tracks spending over time
-- ============================================================================
WITH customer_cohorts AS (
    SELECT 
        shop_id,
        customer_gid,
        DATE_TRUNC('month', first_order_processed_at) as cohort_month
    FROM agg_customer_ltv
    WHERE first_order_processed_at IS NOT NULL
),
order_cohort_data AS (
    SELECT 
        fo.shop_id,
        cc.cohort_month,
        fo.customer_gid,
        DATE_TRUNC('month', fo.processed_at) as order_month,
        fo.net_sales
    FROM fact_orders fo
    INNER JOIN customer_cohorts cc 
        ON fo.shop_id = cc.shop_id 
        AND fo.customer_gid = cc.customer_gid
    WHERE fo.cancelled_at IS NULL
      AND fo.processed_at IS NOT NULL
)
INSERT INTO agg_ltv_cohort_month (
    shop_id,
    cohort_month,
    months_since_first_order,
    customers_in_cohort,
    net_sales,
    cumulative_net_sales
)
SELECT 
    shop_id,
    cohort_month,
    EXTRACT(YEAR FROM AGE(order_month, cohort_month)) * 12 + 
    EXTRACT(MONTH FROM AGE(order_month, cohort_month)) as months_since_first_order,
    COUNT(DISTINCT customer_gid) as customers_in_cohort,
    SUM(net_sales) as net_sales,
    SUM(SUM(net_sales)) OVER (
        PARTITION BY shop_id, cohort_month 
        ORDER BY EXTRACT(YEAR FROM AGE(order_month, cohort_month)) * 12 + 
                 EXTRACT(MONTH FROM AGE(order_month, cohort_month))
    ) as cumulative_net_sales
FROM order_cohort_data
GROUP BY shop_id, cohort_month, months_since_first_order
ON CONFLICT (shop_id, cohort_month, months_since_first_order) DO UPDATE SET
    customers_in_cohort = EXCLUDED.customers_in_cohort,
    net_sales = EXCLUDED.net_sales,
    cumulative_net_sales = EXCLUDED.cumulative_net_sales;

-- ============================================================================
-- ROLLUP 4: Combine Shop Daily Metrics with Ad Spend
-- Rolls up orders data and joins with channel spend data
-- ============================================================================
INSERT INTO agg_shop_day_with_spend (
    shop_id,
    date,
    revenue_gross,
    net_sales,
    orders_count,
    ad_spend_total,
    mer
)
SELECT 
    asd.shop_id,
    asd.date,
    asd.revenue_gross,
    asd.net_sales,
    asd.orders_count,
    COALESCE(channel_spend.total_spend, 0) as ad_spend_total,
    CASE 
        WHEN COALESCE(channel_spend.total_spend, 0) > 0 
        THEN asd.revenue_gross / channel_spend.total_spend
        ELSE 0 
    END as mer
FROM agg_shop_day asd
LEFT JOIN (
    SELECT 
        shop_id,
        date,
        SUM(spend) as total_spend
    FROM fact_channel_day
    GROUP BY shop_id, date
) channel_spend ON asd.shop_id = channel_spend.shop_id 
               AND asd.date = channel_spend.date
ON CONFLICT (shop_id, date) DO UPDATE SET
    revenue_gross = EXCLUDED.revenue_gross,
    net_sales = EXCLUDED.net_sales,
    orders_count = EXCLUDED.orders_count,
    ad_spend_total = EXCLUDED.ad_spend_total,
    mer = EXCLUDED.mer;

-- ============================================================================
-- ANALYSIS QUERIES - Use these to analyze your data
-- ============================================================================

-- Weekly Revenue Rollup
SELECT 
    shop_id,
    DATE_TRUNC('week', date) as week,
    SUM(orders_count) as weekly_orders,
    SUM(revenue_gross) as weekly_revenue,
    SUM(net_sales) as weekly_net_sales,
    ROUND(AVG(revenue_gross), 2) as avg_daily_revenue
FROM agg_shop_day
GROUP BY shop_id, DATE_TRUNC('week', date)
ORDER BY shop_id, week DESC;

-- Monthly Revenue Rollup
SELECT 
    shop_id,
    DATE_TRUNC('month', date) as month,
    SUM(orders_count) as monthly_orders,
    SUM(revenue_gross) as monthly_revenue,
    SUM(net_sales) as monthly_net_sales,
    SUM(new_orders_count) as new_customer_orders,
    SUM(returning_orders_count) as returning_customer_orders
FROM agg_shop_day
GROUP BY shop_id, DATE_TRUNC('month', date)
ORDER BY shop_id, month DESC;

-- Top 10 Customers by LTV
SELECT 
    shop_id,
    customer_gid,
    lifetime_orders_count,
    lifetime_revenue_gross,
    lifetime_net_sales,
    ROUND(lifetime_revenue_gross / lifetime_orders_count, 2) as avg_order_value
FROM agg_customer_ltv
ORDER BY lifetime_revenue_gross DESC
LIMIT 10;

-- Marketing Channel Performance (last 30 days)
SELECT 
    c.channel_name,
    c.channel_type,
    SUM(fcd.spend) as total_spend,
    SUM(fcd.impressions) as total_impressions,
    SUM(fcd.clicks) as total_clicks,
    SUM(fcd.attributed_orders) as total_orders,
    SUM(fcd.attributed_revenue) as total_revenue,
    ROUND(SUM(fcd.attributed_revenue) / NULLIF(SUM(fcd.spend), 0), 2) as roas,
    ROUND(SUM(fcd.clicks)::NUMERIC / NULLIF(SUM(fcd.impressions), 0) * 100, 2) as ctr_percent
FROM fact_channel_day fcd
INNER JOIN dim_channel c ON fcd.channel_id = c.channel_id
WHERE fcd.date >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY c.channel_name, c.channel_type
ORDER BY total_revenue DESC;

-- Cohort Retention Analysis
SELECT 
    cohort_month,
    months_since_first_order,
    customers_in_cohort,
    net_sales,
    cumulative_net_sales,
    ROUND(cumulative_net_sales / customers_in_cohort, 2) as avg_ltv_per_customer
FROM agg_ltv_cohort_month
WHERE shop_id = 1
ORDER BY cohort_month, months_since_first_order;

-- Marketing Efficiency Over Time
SELECT 
    date,
    revenue_gross,
    ad_spend_total,
    orders_count,
    ROUND(mer, 2) as marketing_efficiency_ratio,
    ROUND(revenue_gross / NULLIF(orders_count, 0), 2) as avg_order_value,
    ROUND(ad_spend_total / NULLIF(orders_count, 0), 2) as cac
FROM agg_shop_day_with_spend
WHERE shop_id = 1
ORDER BY date DESC
LIMIT 30;

EOF

print_success "Rollup query examples generated: $ROLLUP_QUERIES_FILE"

################################################################################
# Summary
################################################################################

echo ""
print_success "=============================================="
print_success "Setup Complete!"
print_success "=============================================="
echo ""
print_info "Tables Created:"
echo "  📊 Dimension Tables:"
echo "     - dim_customers"
echo "     - dim_channel"
echo ""
echo "  📈 Fact Tables:"
echo "     - fact_orders"
echo "     - fact_channel_day"
echo ""
echo "  🎯 Aggregate/Rollup Tables:"
echo "     - agg_shop_day (daily metrics)"
echo "     - agg_customer_ltv (customer lifetime value)"
echo "     - agg_ltv_cohort_month (cohort analysis)"
echo "     - agg_shop_day_with_spend (marketing efficiency)"
echo ""
echo "  💾 Raw Payload Tables:"
echo "     - raw_meta_ads"
echo "     - raw_google_ads"
echo ""
print_info "SQL Scripts:"
echo "  - Schema: $TMP_SQL_FILE"
echo "  - Rollup Queries: $ROLLUP_QUERIES_FILE"
if [[ "$DB_TYPE" == "h2" ]]; then
    print_warning "  Note: Rollup queries use PostgreSQL syntax"
    echo "         For H2, the Spring Boot app handles aggregations"
fi
echo ""
print_info "Next Steps:"
echo "  1. Review the generated SQL files"
echo "  2. Execute rollup queries to populate aggregate tables:"
echo "     cat $ROLLUP_QUERIES_FILE | psql ..."
echo "  3. Set up scheduled jobs (cron) to refresh aggregates regularly"
echo "  4. Monitor query performance and add indexes as needed"
echo ""
print_success "🎉 Shopify Analytics Database is ready!"
echo ""
