CREATE TABLE shops (
  shop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_domain VARCHAR(255) NOT NULL UNIQUE,
  currency VARCHAR(3) NOT NULL,
  timezone VARCHAR(64) NOT NULL,
  last_backfill_through TIMESTAMP,
  last_incremental_sync_at TIMESTAMP,
  shopify_access_token_encrypted VARCHAR(512),
  shopify_access_token_iv VARCHAR(64),
  shopify_scopes VARCHAR(512),
  shopify_installed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP,
  deleted_by BIGINT
);

CREATE INDEX idx_shops_domain ON shops (shop_domain);

CREATE TABLE dim_customers (
  shop_id BIGINT NOT NULL,
  customer_gid VARCHAR(128) NOT NULL,
  email VARCHAR(320),
  email_hash VARCHAR(128),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  first_order_processed_at TIMESTAMP,
  last_order_processed_at TIMESTAMP,
  PRIMARY KEY (shop_id, customer_gid),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_dim_customers_shop_email ON dim_customers (shop_id, email);
CREATE INDEX idx_dim_customers_shop_first_order ON dim_customers (shop_id, first_order_processed_at);

CREATE TABLE fact_orders (
  shop_id BIGINT NOT NULL,
  order_gid VARCHAR(128) NOT NULL,
  order_name VARCHAR(128),
  created_at TIMESTAMP,
  processed_at TIMESTAMP,
  updated_at TIMESTAMP,
  cancelled_at TIMESTAMP,
  financial_status VARCHAR(32),
  customer_gid VARCHAR(128),
  gross_total DECIMAL(14,2),
  gross_tax DECIMAL(14,2),
  gross_shipping DECIMAL(14,2),
  net_sales DECIMAL(14,2),
  is_new_customer BOOLEAN,
  PRIMARY KEY (shop_id, order_gid),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_fact_orders_shop_processed ON fact_orders (shop_id, processed_at);
CREATE INDEX idx_fact_orders_shop_updated ON fact_orders (shop_id, updated_at);
CREATE INDEX idx_fact_orders_shop_customer ON fact_orders (shop_id, customer_gid);

CREATE TABLE agg_shop_day (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  orders_count INT DEFAULT 0 NOT NULL,
  revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  tax_total DECIMAL(14,2) DEFAULT 0 NOT NULL,
  shipping_total DECIMAL(14,2) DEFAULT 0 NOT NULL,
  new_orders_count INT DEFAULT 0 NOT NULL,
  returning_orders_count INT DEFAULT 0 NOT NULL,
  new_revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  returning_revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, date),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_agg_shop_day_date ON agg_shop_day (date);

CREATE TABLE agg_customer_ltv (
  shop_id BIGINT NOT NULL,
  customer_gid VARCHAR(128) NOT NULL,
  first_order_processed_at TIMESTAMP,
  last_order_processed_at TIMESTAMP,
  lifetime_orders_count INT DEFAULT 0 NOT NULL,
  lifetime_revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  lifetime_net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, customer_gid),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_agg_customer_ltv_shop_first ON agg_customer_ltv (shop_id, first_order_processed_at);

CREATE TABLE agg_ltv_cohort_month (
  shop_id BIGINT NOT NULL,
  cohort_month DATE NOT NULL,
  months_since_first_order INT NOT NULL,
  customers_in_cohort INT DEFAULT 0 NOT NULL,
  net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  cumulative_net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, cohort_month, months_since_first_order),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_agg_ltv_cohort_month_shop ON agg_ltv_cohort_month (shop_id, cohort_month);

CREATE TABLE dim_channel (
  channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_key VARCHAR(64) NOT NULL UNIQUE,
  channel_name VARCHAR(128) NOT NULL,
  channel_type VARCHAR(32) NOT NULL CHECK (channel_type IN ('paid', 'organic', 'marketplace')),
  status VARCHAR(16) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled'))
);

CREATE TABLE fact_channel_day (
  shop_id BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  date DATE NOT NULL,
  spend DECIMAL(14,2) DEFAULT 0 NOT NULL,
  impressions BIGINT DEFAULT 0 NOT NULL,
  clicks BIGINT DEFAULT 0 NOT NULL,
  attributed_revenue DECIMAL(14,2) DEFAULT 0 NOT NULL,
  attributed_orders INT DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, channel_id, date),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE,
  FOREIGN KEY (channel_id) REFERENCES dim_channel(channel_id)
);

CREATE INDEX idx_fact_channel_day_shop_date ON fact_channel_day (shop_id, date);

CREATE TABLE agg_shop_day_with_spend (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  revenue_gross DECIMAL(14,2) DEFAULT 0 NOT NULL,
  net_sales DECIMAL(14,2) DEFAULT 0 NOT NULL,
  orders_count INT DEFAULT 0 NOT NULL,
  ad_spend_total DECIMAL(14,2) DEFAULT 0 NOT NULL,
  mer DECIMAL(14,6) DEFAULT 0 NOT NULL,
  PRIMARY KEY (shop_id, date),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_agg_shop_day_with_spend_date ON agg_shop_day_with_spend (date);

CREATE TABLE raw_meta_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_raw_meta_ads_shop_date ON raw_meta_ads (shop_id, date);

CREATE TABLE raw_google_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_raw_google_ads_shop_date ON raw_google_ads (shop_id, date);

CREATE TABLE raw_tiktok_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_raw_tiktok_ads_shop_date ON raw_tiktok_ads (shop_id, date);

CREATE TABLE raw_linkedin_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_raw_linkedin_ads_shop_date ON raw_linkedin_ads (shop_id, date);

CREATE TABLE raw_reddit_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_raw_reddit_ads_shop_date ON raw_reddit_ads (shop_id, date);

CREATE TABLE raw_pinterest_ads (
  shop_id BIGINT NOT NULL,
  date DATE NOT NULL,
  payload CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (shop_id, date, created_at),
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE INDEX idx_raw_pinterest_ads_shop_date ON raw_pinterest_ads (shop_id, date);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  primary_shop_id BIGINT NOT NULL,
  role VARCHAR(16) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP,
  deleted_by BIGINT,
  FOREIGN KEY (primary_shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE TABLE user_shops (
  user_id BIGINT NOT NULL,
  shop_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, shop_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE TABLE shop_oauth_state (
  shop_id BIGINT NOT NULL PRIMARY KEY,
  state VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE TABLE shop_bulk_state (
  shop_id BIGINT NOT NULL PRIMARY KEY,
  current_type VARCHAR(32),
  operation_id VARCHAR(255),
  status VARCHAR(32),
  url CLOB,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

CREATE TABLE audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(128) NOT NULL,
  actor_user_id BIGINT,
  actor_email VARCHAR(255),
  target_user_id BIGINT,
  target_shop_id BIGINT,
  metadata CLOB,
  ip_address VARCHAR(64),
  user_agent VARCHAR(512),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_events_action ON audit_events (action);
CREATE INDEX idx_audit_events_actor ON audit_events (actor_user_id);
CREATE INDEX idx_audit_events_target_shop ON audit_events (target_shop_id);

CREATE TABLE shop_rate_limit (
  shop_id BIGINT NOT NULL PRIMARY KEY,
  enabled BOOLEAN DEFAULT TRUE NOT NULL,
  capacity INT NOT NULL,
  refill_per_minute INT NOT NULL,
  FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);
